### ISSUE TITLE
Replace deprecated sphere package

### ISSUE THREAD

**Issue by stsci-hack** [STScI-JWST/jwst#1858]
The image alignment code used by the outlier_detection step still relies on the original spherical geometry package developed and originally used in the HST pipeline; namely, stsci.sphere.  However, it has since been replaced and subsequently deprecated.  The use of this package by the JWST code should be replaced with calls to the new spherical_geometry package instead.

**Comment by pllim** [comment]
Note: This is making RTD fail for the past 3 days. Some intermediate quick-fix might be needed to get RTD to build again. FYI.

**Comment by jdavies-st** [comment]
It looks like outlier_detection doesn't depend on `stsci.sphere` but `tweakreg` and `skymatch` do.  Thoughts @mcara?

**Comment by mcara** [comment]
Link to the opened PR: https://github.com/STScI-JWST/jwst/pull/1859

**Comment by stsci-hack** [comment]
The astroconda dev specification will be modified using ([astroconda dev PR #126](https://github.com/astroconda/astroconda-dev/pull/126) to pick up spherical geometry instead of stsci.sphere, and, as I understand it, allow the RTD build to succeed.

**Comment by pllim** [comment]
I am not convinced that #1859 fixed everything though. RTD and Travis failures were not addressed in that PR, which has since been merged.

**Comment by pllim** [comment]
p.s. I'll give RTD a few minutes to build to see if we need to explicitly list the new dependency on that end. https://readthedocs.org/projects/jwst-pipeline/builds/6986317/

**Comment by pllim** [comment]
Update: RTD failed
```
Running Sphinx v1.7.2
loading translations [en]... done
making output directory...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/reference/objects.inv...
loading intersphinx inventory from http://matplotlib.org/objects.inv...
intersphinx inventory has moved: http://matplotlib.org/objects.inv -> https://matplotlib.org/objects.inv
[autosummary] generating autosummary for: index.rst, jwst/LICENSE.rst, jwst/ami/index.rst, jwst/ami/main.rst, jwst/ami/reference_files.rst, jwst/assign_wcs/asdf-howto.rst, jwst/assign_wcs/exp_types.rst, jwst/assign_wcs/index.rst, jwst/assign_wcs/main.rst, jwst/assign_wcs/reference_files.rst, ..., jwst/wfs_combine/reference_files.rst, jwst/wfs_combine/wfs_combine.rst, jwst/white_light/arguments.rst, jwst/white_light/description.rst, jwst/white_light/index.rst, jwst/white_light/reference_files.rst, jwst/wiimatch/index.rst, jwst/wiimatch/lsq_optimizer.rst, jwst/wiimatch/match.rst, jwst/wiimatch/utils.rst
Failed to import 'jwst.skymatch.skymatch': no module named jwst.skymatch.skymatch
Failed to import 'jwst.skymatch.skymatch_step': no module named jwst.skymatch.skymatch_step
Failed to import 'jwst.skymatch.region': no module named jwst.skymatch.region
Failed to import 'jwst.skymatch.skyimage': no module named jwst.skymatch.skyimage
/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx/application.py", line 233, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx/application.py", line 311, in _init_builder
    self.emit('builder-inited')
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx/application.py", line 444, in emit
    return self.events.emit(event, self, *args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx_automodapi/automodsumm.py", line 255, in process_automodsumm_generation
    lines = automodsumm_to_autosummary_lines(sfn, app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx_automodapi/automodsumm.py", line 327, in automodsumm_to_autosummary_lines
    filestr = automodapi.automodapi_replace(fr.read(), app, True, docname, False)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx_automodapi/automodapi.py", line 277, in automodapi_replace
    modnm, toskip, onlylocals=onlylocals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx_automodapi/automodapi.py", line 388, in _mod_info
    for localnm, fqnm, obj in zip(*find_mod_objs(modname, onlylocals=onlylocals)):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx_automodapi/utils.py", line 78, in find_mod_objs
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/checkouts/latest/jwst/skymatch/__init__.py", line 8, in <module>
    from .skymatch_step import SkyMatchStep
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/checkouts/latest/jwst/skymatch/skymatch_step.py", line 28, in <module>
    from . skymatch import match
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/checkouts/latest/jwst/skymatch/skymatch.py", line 22, in <module>
    from . skyimage import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/checkouts/latest/jwst/skymatch/skyimage.py", line 11
    spherical_geometry"""
The ``skyimage`` module contains algorithms that are used by
``skymatch`` to manage all of the information for footprints (image outlines)
on the sky as well as perform useful operations on these outlines such as
computing intersections and statistics in the overlap regions.

:Authors: Mihai Cara (contact: help@stsci.edu)

:License: :doc:`../LICENSE`

"""
                         
                                                            
                                                                             
                                                                         
                                                              

                                              

                           

  ^
SyntaxError: invalid syntax

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/checkouts/latest/jwst/skymatch/skymatch.py", line 22, in <module>
    from . skyimage import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/checkouts/latest/jwst/skymatch/skyimage.py", line 11
    spherical_geometry"""
The ``skyimage`` module contains algorithms that are used by
``skymatch`` to manage all of the information for footprints (image outlines)
on the sky as well as perform useful operations on these outlines such as
computing intersections and statistics in the overlap regions.

:Authors: Mihai Cara (contact: help@stsci.edu)

:License: :doc:`../LICENSE`

"""
                         
                                                            
                                                                             
                                                                         
                                                              

                                              

                           

  ^
SyntaxError: invalid syntax
```

**Comment by mcara** [comment]
@pllim That is because the **first** line of the `skymatch/skyimage.py` was changed to:
```python
spherical_geometry"""
The ``skyimage`` module contains algorithms that are used by
......................
```
`spherical_geometry` "variable name" should be removed from the from of the docstring.

**Comment by pllim** [comment]
Update: RTD passes again -- `build succeeded, 491 warnings.`

**Comment by nden** [comment]
Is this fixed by #1859?

**Comment by pllim** [comment]
Not sure if related but Travis CI is still failing:
```
Successfully installed sphinx-automodapi-0.7 sphinx-rtd-theme-0.2.4 stsci-rtd-theme-0.0.1
ci-helpers/travis/setup_dependencies_common.sh: line 536:  9974 Segmentation fault      (core dumped) python -c "import matplotlib.pyplot"
```

**Comment by hbushouse** [comment]
And I don't understand why that error is occurring now. PRs #1866, #1867, and #1868, which were just merged in earlier this morning did not throw that error in Travis.

**Comment by pllim** [comment]
I restarted the failed job on latest `master` build. We'll see if it is transient (though builds failed with the same error the last two builds on `master`).

**Comment by pllim** [comment]
Update: Still failing. A pretty persistent transient error, if you ask me.

**Comment by mcara** [comment]
"persistent" AND "transient"?

**Comment by pllim** [comment]
My hunch is that `stsci_rtd_theme` is somehow crashing `matplotlib` import from `ci-helpers`. I don't see this error on Astropy, which also uses the same `ci-helpers`, so whatever you have is local to your package.

**Comment by pllim** [comment]
> Is this fixed... ?

FWIW, I think this particular issue is fixed. However, Travis failure need further investigation, and might be a moot issue if #1864 passes and is merged. Peace out (until your next RTD failure revives my interest here).

**Comment by nden** [comment]
FWIW, the daily gwcs cron job failed with a similar error

```
ci-helpers/travis/setup_dependencies_common.sh: line 536: 10308 Segmentation fault   
   (core dumped) python -c "import matplotlib.pyplot"
```
Did something change in `ci-helpers`? Or a new version of matplotib was included in conda?
